import type{MasterSentence,ReflectionQuestion,ShenPractice}from'./types';

export const shenPractices:ShenPractice[]=[
 {id:'hun-open',shenId:'hun',title:'Yeni Yöne Açıl',durationMinutes:9,description:'Spiral uzanma ve yön değişimleriyle alanı büyüt.',movementIds:['movement-2','movement-3','movement-8'],breathingPatternId:'breath-hun',movementQualityIds:['geniş','akışkan'],difficulty:'beginner'},
 {id:'hun-flow',shenId:'hun',title:'Rüzgâr Gibi Yön Değiştir',durationMinutes:12,description:'Adımları zorlamadan yeni bir akış öğren.',movementIds:['movement-5','movement-10','movement-13'],breathingPatternId:'breath-hun',movementQualityIds:['meraklı','hafif'],difficulty:'intermediate'},
 {id:'yi-center',shenId:'yi',title:'Merkezde Kal',durationMinutes:10,description:'Ağırlığı ölçülü aktar ve niyetini tek hatta tut.',movementIds:['movement-1','movement-7','movement-9'],breathingPatternId:'breath-yi',movementQualityIds:['merkezli','net'],difficulty:'beginner'},
 {id:'yi-repeat',shenId:'yi',title:'Sakin Tekrar',durationMinutes:8,description:'Aynı geçişi acele etmeden üç kez tamamla.',movementIds:['movement-6','movement-9'],breathingPatternId:'breath-yi',movementQualityIds:['ölçülü','kararlı'],difficulty:'beginner'},
 {id:'po-release',shenId:'po',title:'Omuzları Bırak',durationMinutes:8,description:'Nefes verişini uzatıp üst bedendeki fazlalığı azalt.',movementIds:['movement-2','movement-4','movement-18'],breathingPatternId:'breath-po',movementQualityIds:['yumuşak','serbest'],difficulty:'beginner'},
 {id:'po-body',shenId:'po',title:'Bedeni Dinle',durationMinutes:11,description:'Hareket aralarında duyumu ve zemini fark et.',movementIds:['movement-6','movement-11','movement-12'],breathingPatternId:'breath-po',movementQualityIds:['sade','doğal'],difficulty:'intermediate'},
 {id:'zhi-depth',shenId:'zhi',title:'Sessiz Devamlılık',durationMinutes:14,description:'Geçişleri uzat, hız dalgalanmasını azalt.',movementIds:['movement-1','movement-10','movement-16'],breathingPatternId:'breath-zhi',movementQualityIds:['derin','sürekli'],difficulty:'intermediate'},
 {id:'zhi-root',shenId:'zhi',title:'Kökü Koru',durationMinutes:10,description:'Düşük tempoda ağırlık merkezini sakin tut.',movementIds:['movement-7','movement-9','movement-15'],breathingPatternId:'breath-zhi',movementQualityIds:['sakin','ağırbaşlı'],difficulty:'beginner'},
 {id:'xin-whole',shenId:'xin',title:'Nefesle Bütünleş',durationMinutes:12,description:'Nefes ve hareketi tek bir sıcak akışta birleştir.',movementIds:['movement-3','movement-10','movement-13','movement-18'],breathingPatternId:'breath-xin',movementQualityIds:['bütün','uyumlu'],difficulty:'intermediate'},
 {id:'xin-close',shenId:'xin',title:'Sakin Kapanış',durationMinutes:7,description:'Serbest akışı kısa bir farkındalıkla tamamla.',movementIds:['movement-12','movement-18'],breathingPatternId:'breath-xin',movementQualityIds:['sıcak','doğal'],difficulty:'beginner'},
];

export const reflectionQuestions:ReflectionQuestion[]=[
 ['hun-q1','hun','Bugün hangi yöne daha fazla alan açmak istiyorsun?'],['hun-q2','hun','Hareket ederken nerede kendini tuttun?'],['hun-q3','hun','Bugün sana yeni gelen neydi?'],
 ['yi-q1','yi','Bugün dikkatini en kolay ne dağıttı?'],['yi-q2','yi','Hareket boyunca merkezini nerede hissettin?'],['yi-q3','yi','Başlangıçtaki niyetin pratik sonunda değişti mi?'],
 ['po-q1','po','Bugün bedeninin hangi bölgesi senden ilgi istedi?'],['po-q2','po','Neyi daha az güç kullanarak yapabilirdin?'],['po-q3','po','Nefes verirken neyi bıraktığını hissettin?'],
 ['zhi-q1','zhi','Bugün devam etmene ne yardım etti?'],['zhi-q2','zhi','Sessizlik içinde en çok neyi fark ettin?'],['zhi-q3','zhi','Zorlandığında hareketin ritmi nasıl değişti?'],
 ['xin-q1','xin','Bugün hareketin hangi anında kendini bütün hissettin?'],['xin-q2','xin','Pratik ruh hâlini nasıl değiştirdi?'],['xin-q3','xin','Hangi hareket sana daha fazla sıcaklık veya açıklık verdi?'],
].map(([id,shenId,text])=>({id,shenId,text} as ReflectionQuestion));

const sentenceText={
 hun:['Kollar yön aramasın; merkez onlara yolu göstersin.','Açılmak daha uzağa uzanmak değil, içeride yer açmaktır.','Yön değiştirirken kökünü geride bırakma.','Yeni hareketi önce merakla dinle.','Genişlik omuzlarda değil, nefesin çevresinde başlar.','Adımın yolu bakışından önce merkezinde belirsin.','Uzanırken eklemleri kilitleme; yolu açık tut.','Dönüşü itme, ağırlığın seni çevirmesine izin ver.','Hareket büyürken nefesin sakin kalsın.','Esneklik biçimi kaybetmek değil, biçim içinde alan bulmaktır.','İlk adım küçük olabilir; yönü temiz olsun.','Kolların gökyüzünü ararken ayakların yeri hatırlasın.','Yeni akışta hata arama; geçişi gözlemle.','Bedenin bir yöne kapanıyorsa karşı tarafa nefes ver.','Genişlemek için hızlanma.','Uzanışın sonunu değil, başlangıcını yumuşat.','Yol değiştiğinde ritmi yanında götür.','Merak, hareketin gereksiz gücünü azaltır.','Dönüşte gözlerin değil, merkez çizgin önderlik etsin.','Alan aç; hareket kendi büyüklüğünü bulsun.'],
 yi:['Niyetin tek olsun; beden onu parçalara ayırmadan taşısın.','Ağırlığı aktar; bedenini fırlatma.','Merkezini bulmadan kolları göreve gönderme.','Tekrar, aynı hareketi değil aynı dikkati yeniler.','Dikkat dağıldığında ayak tabanına dön.','Ölçü, hareketi küçültmez; görünür kılar.','Geçişin ortasında niyetini kaybetme.','Merkez sabit bir nokta değil, geri döndüğün ilişkidir.','Bir hareketi tamamlamadan sonrakine hazırlanma.','Bakışın sakinleşince yönün netleşir.','Ağırlığın iki ayak arasında acele etmeden konuşsun.','Dizler yönü izlesin, merkez baskı kurmasın.','Netlik, daha fazla komut değil daha az dağınıklıktır.','Hareketi sayma; geçişin bütünlüğünü koru.','Başlangıçtaki niyeti son nefese kadar taşı.','Merkezden çıkan hareket geri dönmenin yolunu bilir.','Bir kez daha yap; bu kez daha dikkatli değil daha bütün ol.','Ağırlık değişirken omuzların sessiz kalsın.','Kararlılık sertlik değildir.','Dikkatini düzeltmeye değil hissetmeye yerleştir.'],
 po:['Omuzlarını taşıma; onların düşmesine izin ver.','Nefesi yönetme; ona alan aç.','Gereksiz gücü bıraktığında hareket eksilmez.','Ayağın yere basmasın, yere yerleşsin.','Nefes verirken çeneni ve ellerini yumuşat.','Bedenin sesini duymak için hareketi biraz azalt.','Kasılmayı yenmeye çalışma; çevresinde alan bul.','Kollar inerken göğsün de dinlensin.','Duyum küçükse dikkatin daha nazik olsun.','Nefesin bittiği yerde hareketi zorlamayı bırak.','Yumuşaklık, kontrolün kaybı değildir.','Bedeni düzeltmeden önce nerede gerildiğini sor.','Avuçlarını sıkma; parmakların nefes alsın.','Omuzların yükseliyorsa hareketi değil çabayı azalt.','Bırakmak çökmek değildir; desteği zemine devretmektir.','Her nefes verişte bir parça fazlalık ayrılsın.','Doğal hareket, en az iş yapan hareket değildir.','Bedenin sınırına yaklaş; onu itme.','Göğsü açmak için kaburgaları zorlama.','Sessizlikte kalan duyumu da pratiğin parçası say.'],
 zhi:['Hızını azaltınca hareket kaybolmaz, görünür olur.','Derinleşmek için daha fazla güç kullanma.','Devamlılık, her gün aynı kuvvette olmak değildir.','Geçişi uzat; iradeyi kaslarda toplama.','Sakinlik durmak değil, ritmi koruyabilmektir.','Zorlandığında hareketi küçült, bağı koparma.','Kök, ağırlığın yere bıraktığı sessiz karardır.','Bekleme anında bedenini terk etme.','Uzun nefes, uzun bir hareketten daha değerlidir.','Denge, hiç sallanmamak değil; geri dönebilmektir.','Yavaşlık içinde dikkatin uyumasına izin verme.','Bir sonraki adıma gücünü saklayarak geç.','İrade, bedeni zorlamak değil pratiğe geri dönmektir.','Ayakların ağırlaşırken başın hafif kalsın.','Karanlık bir geçişte yönü nefes korur.','Süreyi tamamlamak için biçimi feda etme.','Her tekrar kökü biraz daha sessiz kurar.','Derin su acele etmez; yönünü yine de bulur.','Hareketin ortasında kalabilmek de ilerlemedir.','Son pozda donma; devamın ihtimalini koru.'],
 xin:['Hareketi itme; ağırlığın yolunu aç.','Eller yolu gösterir, merkez hareketi başlatır.','Nefes ve hareket buluştuğunda fazladan komut gerekmez.','Sıcaklık göğüste kalmasın, bütün bedene dağılsın.','Bütünlük parçaları aynılaştırmak değildir.','Kapanışta hareketi kesme; sessizliğe bırak.','Kollar başlamadan önce merkez yönünü bulsun.','Gücü kaslarda toplama; bütün bedene dağıt.','Yumuşak ifade, net yönle birlikte yaşayabilir.','Hareketin sonunda kendine geri dön.','Bağ kurmak için biçimi zorlaman gerekmez.','Canlılık hızdan değil katılımdan gelir.','Nefesin ritmi bedene ortak bir dil versin.','Kalbin açıklığı omuzların yumuşaklığında görünsün.','Serbest akış, dikkatsiz akış değildir.','Bir hareket diğerini taşısın; aralarında kopukluk bırakma.','Sakin kapanış pratiğin sonu değil, günün başlangıcıdır.','Bedenin farklı parçaları aynı niyeti paylaşsın.','Hareket tamamlandığında geride sıcak bir iz kalsın.','Boşluk, hareketin eksikliği değil; başlangıcıdır.'],
}as const;
export const masterSentences:MasterSentence[]=Object.entries(sentenceText).flatMap(([shenId,texts])=>texts.map((text,index)=>({
 id:`master-${shenId}-${String(index+1).padStart(2,'0')}`,text,shenId:shenId as MasterSentence['shenId'],tags:index%3===0?['merkez','denge']:index%3===1?['nefes','akış']:['ağırlık','yumuşaklık'],difficulty:index<8?'beginner':index<15?'intermediate':'advanced',createdAt:'2026-07-29T00:00:00.000Z',
})));

