export const palette = {
  background: "#0B0E12",
  backgroundSecondary: "#14181C",
  card: "#20252B",
  pressed: "#292E34",
  border: "rgba(232,222,205,0.12)",
  text: "#F2EEE7",
  textSecondary: "#A7ADA6",
  divider: "#343A40",
  gold: "#C8A56A",
  bronze: "#A67C52",
  ivory: "#E8DECD",
  mist: "#9EA7AA",
  success: "#84A96C",
  posePoint: "#A9D977",
  warning: "#D49A58",
  destructive: "#B76555",
} as const;

export const spacing = {
  x1: 4,
  x2: 8,
  x3: 12,
  x4: 16,
  x6: 24,
  x8: 32,
  x12: 48,
  x16: 64,
} as const;

export const radii = {
  control: 16,
  card: 20,
  cardLarge: 24,
  round: 999,
} as const;

export const motion = {
  quick: 600,
  standard: 900,
  slow: 1200,
  ritual: 1600,
  easing: "cubic-bezier(0.4, 0, 0.2, 1)",
} as const;

export const typography = {
  display: "Cormorant Garamond",
  ui: "Inter",
  metric: "Manrope",
  mobileDisplayMax: 44,
  desktopDisplayMax: 64,
} as const;

export const shenThemes = {
  hun: {
    id: "hun",
    name: "Hun",
    element: "Ağaç",
    primary: "#91A867",
    dark: "#46543D",
    light: "#D1DAAD",
    backgroundImage: "/images/shen-river-hun.jpg",
    backgroundOverlay: "rgba(10,15,12,0.78)",
    icon: "leaf-outline",
    shortDescription: "Gün doğumu, yön ve umut",
    ambientMotion: "mist",
    accentUsage: "selected-control",
    surface: "#172019",
    surfaceRaised: "#233025",
    button: "#B9CF78",
    buttonInk: "#11170F",
    controlRadius: 18,
    headingWeight: "500",
    headingTracking: "0.01em",
    transitionMs: 520,
  },
  yi: {
    id: "yi",
    name: "Yi",
    element: "Dikkat",
    primary: "#C7BFAE",
    dark: "#6F6A62",
    light: "#EEE8DC",
    backgroundImage: "/images/shen-river-po.jpg",
    backgroundOverlay: "rgba(10,15,12,0.8)",
    icon: "ellipse-outline",
    shortDescription: "Sis, dikkat ve iç denge",
    ambientMotion: "fog",
    accentUsage: "selected-control",
    surface: "#202120",
    surfaceRaised: "#2C2D2B",
    button: "#EEE8DC",
    buttonInk: "#171817",
    controlRadius: 12,
    headingWeight: "500",
    headingTracking: "-0.02em",
    transitionMs: 420,
  },
  po: {
    id: "po",
    name: "Po",
    element: "Toprak",
    primary: "#B69268",
    dark: "#604D3C",
    light: "#DCC7AA",
    backgroundImage: "/images/shen-river-yi.jpg",
    backgroundOverlay: "rgba(10,15,12,0.82)",
    icon: "moon-outline",
    shortDescription: "Güven, merkez ve sakin güç",
    ambientMotion: "still",
    accentUsage: "selected-control",
    surface: "#221D19",
    surfaceRaised: "#312820",
    button: "#D9B47D",
    buttonInk: "#1C140E",
    controlRadius: 8,
    headingWeight: "600",
    headingTracking: "0em",
    transitionMs: 360,
  },
  zhi: {
    id: "zhi",
    name: "Zhi",
    element: "Su",
    primary: "#688AA1",
    dark: "#263846",
    light: "#B9D0DA",
    backgroundImage: "/images/shen-river-zhi.jpg",
    backgroundOverlay: "rgba(10,15,12,0.82)",
    icon: "water-outline",
    shortDescription: "Derinlik, sessizlik ve içsel irade",
    ambientMotion: "water",
    accentUsage: "selected-control",
    surface: "#121C23",
    surfaceRaised: "#1C2B35",
    button: "#9CC3D4",
    buttonInk: "#0C151B",
    controlRadius: 28,
    headingWeight: "400",
    headingTracking: "0.025em",
    transitionMs: 620,
  },
  shen: {
    id: "shen",
    name: "Shen",
    element: "Birlik",
    primary: "#D1AE68",
    dark: "#6C5638",
    light: "#F0D9A6",
    backgroundImage: "/images/shen-river-shen.jpg",
    backgroundOverlay: "rgba(10,15,12,0.8)",
    icon: "heart-outline",
    shortDescription: "Altın ışık, huzur ve birlik",
    ambientMotion: "golden-light",
    accentUsage: "selected-control",
    surface: "#211C15",
    surfaceRaised: "#30271B",
    button: "#E4BE70",
    buttonInk: "#191208",
    controlRadius: 999,
    headingWeight: "600",
    headingTracking: "0.045em",
    transitionMs: 460,
  },
} as const;

export type SharedShenId = keyof typeof shenThemes;

export const designTokens = {
  palette,
  spacing,
  radii,
  motion,
  typography,
  shenThemes,
} as const;
