"use client";

import Link from"next/link";
import{type CSSProperties,type MutableRefObject,useCallback,useEffect,useMemo,useRef,useState}from"react";
import{analyzeDynamicMovement,analyzeStaticPractice,buildShortFlowReferenceFrames,getStaticPractice,interpolatePractice2Reference,shortFlowDefinitions,shortFlowStepAt,staticPracticeDefinitions,staticReferencePoses,type Practice2Analysis,type Practice2PosePoint,type Practice2PoseSample}from"../../../packages/practice2";
import styles from"./practice2.module.css";

const landmarkNames=['nose','left_eye_inner','left_eye','left_eye_outer','right_eye_inner','right_eye','right_eye_outer','left_ear','right_ear','mouth_left','mouth_right','left_shoulder','right_shoulder','left_elbow','right_elbow','left_wrist','right_wrist','left_pinky','right_pinky','left_index','right_index','left_thumb','right_thumb','left_hip','right_hip','left_knee','right_knee','left_ankle','right_ankle','left_heel','right_heel','left_foot_index','right_foot_index'];
const connections:ReadonlyArray<readonly[string,string]>=[['left_shoulder','right_shoulder'],['left_shoulder','left_elbow'],['left_elbow','left_wrist'],['right_shoulder','right_elbow'],['right_elbow','right_wrist'],['left_shoulder','left_hip'],['right_shoulder','right_hip'],['left_hip','right_hip'],['left_hip','left_knee'],['left_knee','left_ankle'],['right_hip','right_knee'],['right_knee','right_ankle']];
const DYNAMIC_PREVIEW_MS=4500;
const STATIC_CAPTURE_THRESHOLD=70;
const STATIC_CAPTURE_HOLD_MS=1500;
type StaticCaptureState='idle'|'matching'|'hold'|'saved';
export type Practice2SnapshotCapture={id:string;dateKey:string;timeLabel:string;createdAt:string;movementId:number;movementName:string;score:number;shenName:string;imageData:string;trainerVisible?:boolean;source?:'practice2'};
export function Practice2Screen({embedded=false,onSnapshotCaptured,selectedShenName='Beş Shen'}:{embedded?:boolean;onSnapshotCaptured?:(snapshot:Practice2SnapshotCapture)=>void;selectedShenName?:string}){
 const camera=usePractice2Camera(),[mobileMode,setMobileMode]=useState<'static'|'dynamic'>('static'),[selectedStatic,setSelectedStatic]=useState(0),[selectedFlow,setSelectedFlow]=useState(0),[staticActive,setStaticActive]=useState(false),[staticSeconds,setStaticSeconds]=useState(0),[staticAnalysis,setStaticAnalysis]=useState<Practice2Analysis|null>(null),[staticCaptureState,setStaticCaptureState]=useState<StaticCaptureState>('idle'),[staticHoldProgress,setStaticHoldProgress]=useState(0),[dynamicRunning,setDynamicRunning]=useState(false),[dynamicElapsed,setDynamicElapsed]=useState(0),[dynamicAnalysis,setDynamicAnalysis]=useState<Practice2Analysis|null>(null),[dynamicCaptureState,setDynamicCaptureState]=useState<StaticCaptureState>('idle'),[dynamicHoldProgress,setDynamicHoldProgress]=useState(0);
 const staticHistory=useRef<Practice2PoseSample[]>([]),staticMatchedAt=useRef(0),staticCaptured=useRef(false),staticCaptureRef=useRef<(()=>string|null)|null>(null),dynamicHistory=useRef<Practice2PoseSample[]>([]),dynamicMatchedAt=useRef(0),dynamicCaptured=useRef(false),dynamicCaptureRef=useRef<(()=>string|null)|null>(null),dynamicStartedAt=useRef(0),dynamicCarried=useRef(0);
 const selectedPractice=staticPracticeDefinitions[selectedStatic],targetPose=staticReferencePoses[selectedPractice.id],flow=shortFlowDefinitions[selectedFlow],flowDurationMs=DYNAMIC_PREVIEW_MS,flowFrames=useMemo(()=>buildShortFlowReferenceFrames(flow,DYNAMIC_PREVIEW_MS),[flow]),activeFlowStep=shortFlowStepAt(flow,dynamicElapsed,flowDurationMs),reference=interpolatePractice2Reference(dynamicElapsed,flowFrames);

 useEffect(()=>{if(!staticActive)return;const timer=setInterval(()=>setStaticSeconds(value=>value+1),1000);return()=>clearInterval(timer)},[staticActive]);
 useEffect(()=>{if(staticActive&&staticSeconds*1000>=selectedPractice.holdDurationMs)setStaticActive(false)},[selectedPractice.holdDurationMs,staticActive,staticSeconds]);
 useEffect(()=>{if(!dynamicRunning)return;dynamicStartedAt.current=performance.now();let frame=0;const tick=(now:number)=>{const next=Math.min(flowDurationMs,dynamicCarried.current+now-dynamicStartedAt.current);setDynamicElapsed(next);if(next>=flowDurationMs){dynamicCarried.current=flowDurationMs;setDynamicRunning(false);return}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[dynamicRunning,flowDurationMs]);
 useEffect(()=>{if(!camera.pose.length)return;const timestamp=Date.now();if(staticActive){const sample={timestampMs:timestamp,keypoints:camera.pose};staticHistory.current=[...staticHistory.current.slice(-29),sample];const analysis=analyzeStaticPractice(staticHistory.current,sample,targetPose);setStaticAnalysis(analysis);const score=analysis.overallScore??0;if(score>=STATIC_CAPTURE_THRESHOLD&&!staticCaptured.current){if(!staticMatchedAt.current)staticMatchedAt.current=timestamp;const elapsed=timestamp-staticMatchedAt.current;setStaticCaptureState('hold');setStaticHoldProgress(Math.min(100,Math.round(elapsed/STATIC_CAPTURE_HOLD_MS*100)));if(elapsed>=STATIC_CAPTURE_HOLD_MS){const imageData=staticCaptureRef.current?.();if(imageData){staticCaptured.current=true;playCaptureClick();const createdAt=new Date();onSnapshotCaptured?.({id:`practice2-${createdAt.getTime()}`,dateKey:formatSnapshotDate(createdAt),timeLabel:formatSnapshotTime(createdAt),createdAt:createdAt.toISOString(),movementId:selectedPractice.order,movementName:selectedPractice.title,score,shenName:selectedShenName,imageData,trainerVisible:false,source:'practice2'});setStaticCaptureState('saved');setStaticHoldProgress(100);setStaticActive(false)}}}else if(!staticCaptured.current){staticMatchedAt.current=0;setStaticCaptureState('matching');setStaticHoldProgress(0)}}if(dynamicRunning){const sample={timestampMs:dynamicElapsed,keypoints:camera.pose};dynamicHistory.current=[...dynamicHistory.current.slice(-49),sample];const analysis=analyzeDynamicMovement(dynamicHistory.current,sample,flowFrames);setDynamicAnalysis(analysis);const score=analysis.overallScore??0;if(score>=STATIC_CAPTURE_THRESHOLD&&!dynamicCaptured.current){if(!dynamicMatchedAt.current)dynamicMatchedAt.current=timestamp;const elapsed=timestamp-dynamicMatchedAt.current;setDynamicCaptureState('hold');setDynamicHoldProgress(Math.min(100,Math.round(elapsed/STATIC_CAPTURE_HOLD_MS*100)));if(elapsed>=STATIC_CAPTURE_HOLD_MS){const imageData=dynamicCaptureRef.current?.();if(imageData){dynamicCaptured.current=true;playCaptureClick();const createdAt=new Date();onSnapshotCaptured?.({id:`practice2-flow-${createdAt.getTime()}`,dateKey:formatSnapshotDate(createdAt),timeLabel:formatSnapshotTime(createdAt),createdAt:createdAt.toISOString(),movementId:flow.order,movementName:`${flow.title} · Akış`,score,shenName:selectedShenName,imageData,trainerVisible:false,source:'practice2'});setDynamicCaptureState('saved');setDynamicHoldProgress(100);setDynamicRunning(false)}}}else if(!dynamicCaptured.current){dynamicMatchedAt.current=0;setDynamicCaptureState('matching');setDynamicHoldProgress(0)}}},[camera.pose,dynamicElapsed,dynamicRunning,flow.order,flow.title,flowFrames,onSnapshotCaptured,selectedPractice.order,selectedPractice.title,selectedShenName,staticActive,targetPose]);

 const beginStatic=async()=>{await camera.start();staticHistory.current=[];staticMatchedAt.current=0;staticCaptured.current=false;setStaticSeconds(0);setStaticAnalysis(null);setStaticCaptureState('matching');setStaticHoldProgress(0);setStaticActive(true)};
 const finishStatic=()=>setStaticActive(false);
 const beginDynamic=async()=>{await camera.start();dynamicHistory.current=[];dynamicMatchedAt.current=0;dynamicCaptured.current=false;dynamicCarried.current=0;setDynamicElapsed(0);setDynamicAnalysis(null);setDynamicCaptureState('matching');setDynamicHoldProgress(0);setDynamicRunning(true)};
 const toggleDynamic=()=>setDynamicRunning(current=>{if(current){dynamicCarried.current=dynamicElapsed}else if(dynamicElapsed>=flowDurationMs){dynamicCarried.current=0;setDynamicElapsed(0)}return!current});

 return <main className={`${styles.page} ${embedded?styles.embedded:''}`}>
  {!embedded?<header className={styles.header}><Link href="/" className={styles.brand}><i/>SHIBASHI <span>EFE</span></Link><div><h1>PRATİK MODU</h1><p>Alıştır. Hisset. Ustalık Kazan.</p></div><Link href="/">Uygulamaya dön</Link></header>:<div className={styles.embeddedTitle}><p>PRATİK2 · GERÇEK ANALİZ</p><h1>Pratik Modu</h1><span>Statik duruş ve dinamik akış aynı ölçüm dilinde.</span></div>}
  <div className={styles.segment}><button className={mobileMode==='static'?styles.segmentActive:''} onClick={()=>setMobileMode('static')} type="button">1 · Statik Pozlar</button><button className={mobileMode==='dynamic'?styles.segmentActive:''} onClick={()=>setMobileMode('dynamic')} type="button">2 · Akış Hareketleri</button></div>
  <div className={styles.singleScreen}>
   {mobileMode==='static'?<section className={`${styles.module} ${styles.staticModule}`}>
    <div className={styles.staticPicker}>{staticPracticeDefinitions.map((item,index)=><button className={selectedStatic===index?styles.staticSelected:''} key={item.id} onClick={()=>{setSelectedStatic(index);setStaticAnalysis(null);setStaticActive(false)}} type="button"><img alt="" src={item.referenceImage}/><span><b>{String(item.order).padStart(2,'0')} · {item.title}</b><small>{item.englishTitle} · {item.cameraView}</small></span></button>)}</div>
    <div className={styles.staticStage}>
     <div className={styles.staticCameraPortrait}>
      <CameraSurface camera={camera} captureRef={staticCaptureRef} showPose/><div className={styles.stageShade}/>
      <div className={styles.staticHud}>
       {staticActive?<div className={styles.staticTime}><strong>{formatTime(staticSeconds)}</strong><span>/ {Math.round(selectedPractice.holdDurationMs/1000)} sn</span></div>:<span/>}
       <ScoreRing score={staticAnalysis?.overallScore??null} label="Poz uyumu"/>
      </div>
      <div className={`${styles.captureCue} ${staticCaptureState==='hold'?styles.captureCueHold:''} ${staticCaptureState==='saved'?styles.captureCueSaved:''}`}>
       <strong>{staticCaptureState==='hold'?'Bekle · pozu koru':staticCaptureState==='saved'?'✓ Fotoğraf galeriye kaydedildi':staticAnalysis?.overallScore===null||!staticAnalysis?'Tam bedenini kadraja al':`${STATIC_CAPTURE_THRESHOLD}% uyuma ulaş`}</strong>
       <span>{staticCaptureState==='hold'?'Kıpırdama; fotoğrafın hazırlanıyor.':staticCaptureState==='saved'?'Günlükte tarih, skor ve eğitmen paylaşımıyla hazır.':'Yeşil noktaları referanstaki beden hattıyla eşleştir.'}</span>
       {staticCaptureState==='hold'?<i style={{width:`${staticHoldProgress}%`}}/>:null}
      </div>
      <div className={styles.staticControl}><button onClick={staticActive?finishStatic:beginStatic} type="button">{staticActive?'Duruşu bitir':'Kamerayı aç ve pozu dene'}</button></div>
     </div>
     <aside className={styles.staticSidePanel}>
      <div className={styles.staticReference}><small>YANDAKİ POZU YAP</small><img alt={`${selectedPractice.title} hedef pozu`} src={selectedPractice.referenceImage}/><strong>{selectedPractice.title}</strong><span>{selectedPractice.cameraView==='front'?'Kameraya dön':selectedPractice.cameraView==='side'?'Yandan dur':'Hafif çapraz dur'}</span></div>
      <div className={styles.staticScore}><span>{staticAnalysis?.overallScore===null||!staticAnalysis?'Baş, omuz, kalça, diz ve ayak bileklerin görünür olduğunda gerçek skor başlayacak.':staticAnalysis.overallScore>=85?'Hedef poza çok yakınsın; sabit kal.':staticAnalysis.overallScore>=70?'Eşik tamam. Fotoğraf için bekle.':'Referans poza bakıp beden hattını yeniden yerleştir.'}</span></div>
     </aside>
    </div>
   </section>:null}

   {mobileMode==='dynamic'?<section className={styles.module}>
    <ModuleHeader index="2" title="Dinamik Hareket – Akış Pratiği" note="Referans dizisini izle ve aynı akışı kamera önünde uygula." action="Akış Alıştırması"/>
    <div className={styles.flowPicker}>{shortFlowDefinitions.map((item,index)=><button className={selectedFlow===index?styles.flowSelected:''} key={item.id} onClick={()=>{setSelectedFlow(index);setDynamicRunning(false);setDynamicAnalysis(null);setDynamicElapsed(0)}} type="button"><span>{String(item.order).padStart(2,'0')}</span><strong>{item.title}</strong><small>4,5 sn · hareket ön izlemesi</small><em>{item.focus}</em></button>)}</div>
    <div className={styles.dynamicPracticeStage}>
     <div className={styles.dynamicCameraPortrait}>
      <CameraSurface camera={camera} captureRef={dynamicCaptureRef}/><div className={styles.stageShade}/>
      <div className={styles.staticHud}><div className={styles.liveTime}><strong>{(dynamicElapsed/1000).toFixed(1)}</strong><small>/ 4,5 sn</small></div><ScoreRing score={dynamicAnalysis?.overallScore??null} label="Akış uyumu"/></div>
      <div className={`${styles.captureCue} ${dynamicCaptureState==='hold'?styles.captureCueHold:''} ${dynamicCaptureState==='saved'?styles.captureCueSaved:''}`}><strong>{dynamicCaptureState==='hold'?'Bekle · akışı koru':dynamicCaptureState==='saved'?'✓ Akış fotoğrafı galeriye kaydedildi':dynamicAnalysis?.overallScore===null||!dynamicAnalysis?'Tam bedenini kadraja al':`${STATIC_CAPTURE_THRESHOLD}% akış uyumuna ulaş`}</strong><span>{dynamicCaptureState==='hold'?'Kıpırdama; klik sesiyle kaydedilecek.':dynamicCaptureState==='saved'?'Tarih ve skoruyla Günlük arşivinde hazır.':activeFlowStep.cue}</span>{dynamicCaptureState==='hold'?<i style={{width:`${dynamicHoldProgress}%`}}/>:null}</div>
      <div className={styles.liveTimeline}>{flow.steps.map((item,index)=><i className={item.practiceId===activeFlowStep.practiceId?styles.timelineActive:''} key={`${flow.id}-${item.practiceId}-${index}`}/>)}</div>
      <div className={styles.staticControl}><button onClick={dynamicRunning?()=>setDynamicRunning(false):beginDynamic} type="button">{dynamicRunning?'Akışı durdur':'Kamerayı aç ve akışı dene'}</button></div>
     </div>
     <aside className={styles.dynamicSidePanel}>
      <div className={styles.dynamicReference}><small>HAREKETLİ REFERANSI TAKİP ET</small><div className={styles.dynamicReferenceMedia}><img key={`${flow.id}-${activeFlowStep.practiceId}`} alt={`${flow.title} referans sahnesi`} src={getStaticPractice(activeFlowStep.practiceId).referenceImage}/><div className={styles.referenceFigure}><PoseFigure pose={reference.keypoints}/></div></div><strong>{flow.title}</strong><span>{activeFlowStep.cue}</span><div className={styles.referenceControls}><button onClick={toggleDynamic} type="button">{dynamicRunning?'Ⅱ':'▶'}</button><span>{(dynamicElapsed/1000).toFixed(1)} / 4,5 sn</span><div><i style={{width:`${dynamicElapsed/flowDurationMs*100}%`}}/></div></div></div>
      <MetricPanel title="Akış Analizi" analysis={dynamicAnalysis} fallback="Akışı başlatınca gerçek zamanlı ölçümler görünür."/>
     </aside>
    </div>
    <FeedbackPanel analysis={dynamicAnalysis}/>
   </section>:null}
  </div>
  <video className={styles.detectorVideo} muted playsInline ref={camera.detectorVideoRef}/>
 </main>;
}

function ModuleHeader({index,title,note,action}:{index:string;title:string;note:string;action:string}){return <div className={styles.moduleHeader}><div><h2>{index}. {title}</h2><p>{note}</p></div><span>{action}</span></div>}
function ScoreRing({score,label}:{score:number|null;label:string}){return <div className={styles.scoreRing} style={{'--score':score??0}as CSSProperties}><strong>{score===null?'—':`${score}%`}</strong><small>{label}</small></div>}
function MetricPanel({title,analysis,fallback,compact=false}:{title:string;analysis:Practice2Analysis|null;fallback:string;compact?:boolean}){const metrics=analysis?.metrics??[];return <section className={`${styles.metricPanel} ${compact?styles.metricCompact:''}`}><h3>{title}</h3>{metrics.length?metrics.map(item=><div className={styles.metricRow} key={item.id}><div><strong>{item.label}</strong><small>{item.detail}</small></div>{item.available?<><span><i style={{width:`${item.value??0}%`}}/></span><b>{item.value}%</b></>:<em>Henüz ölçülemiyor</em>}</div>):<p className={styles.empty}>{fallback}</p>}{analysis?.overallScore!==null&&analysis?<div className={styles.metricTotal}><span>Toplam uyum</span><strong>{analysis.overallScore}%</strong></div>:null}</section>}
function FeedbackPanel({analysis}:{analysis:Practice2Analysis|null}){return <section className={styles.feedbackPanel}><h3>Geri Bildirim</h3>{analysis?.correction?<p className={styles.correction}><span>△</span>{analysis.correction}</p>:null}{analysis?.positive?<p className={styles.positive}><span>✓</span>{analysis.positive}</p>:null}{!analysis?<p className={styles.empty}>Aynı anda yalnızca bir düzeltme ve bir olumlu işaret göreceksin.</p>:null}<div className={styles.master}><small>USTADAN NOT</small><strong>“Duruş, hareketin köküdür. Kökün güçlenirse dalın hafifler.”</strong></div></section>}
function PoseFigure({pose}:{pose:readonly Practice2PosePoint[]}){const find=(name:string)=>pose.find(item=>item.name===name);return <svg viewBox="0 0 100 100" aria-hidden="true">{connections.map(([a,b])=>{const p1=find(a),p2=find(b);return p1&&p2?<line key={`${a}-${b}`} x1={p1.x*100} y1={p1.y*100} x2={p2.x*100} y2={p2.y*100}/>:null})}{pose.filter(item=>connections.flat().includes(item.name)).map(item=><circle key={item.name} cx={item.x*100} cy={item.y*100} r="1.4"/>)}</svg>}
function CameraSurface({camera,captureRef,placeholder,showPose=true}:{camera:ReturnType<typeof usePractice2Camera>;captureRef?:MutableRefObject<(()=>string|null)|null>;placeholder?:string;showPose?:boolean}){const videoRef=useRef<HTMLVideoElement>(null),canvasRef=useRef<HTMLCanvasElement>(null);useEffect(()=>{const video=videoRef.current;if(!video||!camera.stream)return;video.srcObject=camera.stream;void video.play()},[camera.stream]);useEffect(()=>{if(showPose)drawPose(canvasRef.current,videoRef.current,camera.pose);else canvasRef.current?.getContext('2d')?.clearRect(0,0,canvasRef.current.width,canvasRef.current.height)},[camera.pose,showPose]);useEffect(()=>{if(!captureRef)return;captureRef.current=()=>captureCameraFrame(videoRef.current,canvasRef.current,showPose);return()=>{captureRef.current=null}},[captureRef,showPose]);return <>{placeholder&&camera.status!=='ready'?<img alt="Seçili statik duruş referansı" className={styles.stagePlaceholder} src={placeholder}/>:null}<video className={styles.cameraVideo} muted playsInline ref={videoRef}/>{showPose?<canvas className={styles.poseCanvas} ref={canvasRef}/>:null}{camera.status!=='ready'&&!placeholder?<div className={styles.cameraEmpty}><span>{camera.status==='requesting'?'Kamera izni bekleniyor':camera.status==='denied'?'Kamera izni verilmedi':camera.status==='error'?'Kamera açılamadı':'Kamerayı açınca dikey tam beden analizi başlayacak'}</span></div>:null}</>}
function usePractice2Camera(){const detectorVideoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),animationRef=useRef(0),[stream,setStream]=useState<MediaStream|null>(null),[pose,setPose]=useState<Practice2PosePoint[]>([]),[status,setStatus]=useState<'idle'|'requesting'|'ready'|'denied'|'error'>('idle');const start=useCallback(async()=>{if(streamRef.current)return;setStatus('requesting');try{const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:1280},aspectRatio:{ideal:9/16}},audio:false}),video=detectorVideoRef.current;streamRef.current=next;setStream(next);if(!video)return;video.srcObject=next;await video.play();const{createPoseLandmarker}=await import('@/lib/pose/createPoseLandmarker'),detector=await createPoseLandmarker();let last=0;const run=(now:number)=>{animationRef.current=requestAnimationFrame(run);if(now-last<100||video.readyState<2)return;last=now;const result=detector.detectForVideo(video,now),landmarks=result.landmarks[0];if(!landmarks?.length){setPose([]);return}setPose(landmarks.map((item,index)=>({name:landmarkNames[index]??`point-${index}`,x:item.x,y:item.y,z:item.z,score:item.visibility??1})))};setStatus('ready');animationRef.current=requestAnimationFrame(run)}catch(error){setStatus(error instanceof DOMException&&(error.name==='NotAllowedError'||error.name==='PermissionDeniedError')?'denied':'error')}},[]);useEffect(()=>()=>{cancelAnimationFrame(animationRef.current);streamRef.current?.getTracks().forEach(track=>track.stop())},[]);return{detectorVideoRef,pose,start,status,stream}}
function drawPose(canvas:HTMLCanvasElement|null,video:HTMLVideoElement|null,pose:readonly Practice2PosePoint[]){if(!canvas||!video)return;const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(rect.height*ratio));const context=canvas.getContext('2d');if(!context)return;context.setTransform(ratio,0,0,ratio,0,0);context.clearRect(0,0,rect.width,rect.height);const sourceWidth=video.videoWidth||rect.width,sourceHeight=video.videoHeight||rect.height,scale=Math.max(rect.width/sourceWidth,rect.height/sourceHeight),offsetX=(rect.width-sourceWidth*scale)/2,offsetY=(rect.height-sourceHeight*scale)/2,get=(name:string)=>{const item=pose.find(point=>point.name===name&&(point.score??1)>=.42);if(!item)return null;return{x:rect.width-(item.x*sourceWidth*scale+offsetX),y:item.y*sourceHeight*scale+offsetY}};context.lineCap='round';context.lineWidth=2.2;context.strokeStyle='rgba(169,217,119,.82)';for(const[a,b]of connections){const p1=get(a),p2=get(b);if(!p1||!p2)continue;context.beginPath();context.moveTo(p1.x,p1.y);context.lineTo(p2.x,p2.y);context.stroke()}for(const name of new Set(connections.flat())){const point=get(name);if(!point)continue;context.fillStyle='#F2EEE7';context.beginPath();context.arc(point.x,point.y,4.3,0,Math.PI*2);context.fill();context.fillStyle='#A9D977';context.beginPath();context.arc(point.x,point.y,2.6,0,Math.PI*2);context.fill()}}
function formatTime(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function captureCameraFrame(video:HTMLVideoElement|null,poseCanvas:HTMLCanvasElement|null,includePose:boolean){if(!video||video.readyState<2)return null;const rect=video.getBoundingClientRect(),width=Math.max(360,Math.round(rect.width*1.5)),height=Math.max(640,Math.round(rect.height*1.5)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');if(!context)return null;const sourceWidth=video.videoWidth,sourceHeight=video.videoHeight,scale=Math.max(width/sourceWidth,height/sourceHeight),drawWidth=sourceWidth*scale,drawHeight=sourceHeight*scale,offsetX=(width-drawWidth)/2,offsetY=(height-drawHeight)/2;context.save();context.translate(width,0);context.scale(-1,1);context.drawImage(video,offsetX,offsetY,drawWidth,drawHeight);context.restore();if(includePose&&poseCanvas)context.drawImage(poseCanvas,0,0,width,height);return canvas.toDataURL('image/jpeg',.88)}
function playCaptureClick(){try{const AudioContextClass=window.AudioContext??((window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext);if(!AudioContextClass)return;const context=new AudioContextClass(),now=context.currentTime,gain=context.createGain(),oscillator=context.createOscillator();oscillator.type='square';oscillator.frequency.setValueAtTime(1050,now);oscillator.frequency.exponentialRampToValueAtTime(220,now+.055);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.18,now+.004);gain.gain.exponentialRampToValueAtTime(.0001,now+.07);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(now);oscillator.stop(now+.075);oscillator.addEventListener('ended',()=>void context.close())}catch{/* Kamera kaydı ses olmadan da tamamlanır. */}}
function formatSnapshotDate(date:Date){return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'long',year:'numeric'}).format(date)}
function formatSnapshotTime(date:Date){return new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(date)}
