"use client";

import Link from"next/link";
import{type CSSProperties,useCallback,useEffect,useMemo,useRef,useState}from"react";
import{analyzeDynamicMovement,analyzeStaticPractice,buildShortFlowReferenceFrames,getStaticPractice,interpolatePractice2Reference,shortFlowDefinitions,shortFlowStepAt,staticPracticeDefinitions,staticReferencePoses,type Practice2Analysis,type Practice2PosePoint,type Practice2PoseSample}from"../../../packages/practice2";
import styles from"./practice2.module.css";

const landmarkNames=['nose','left_eye_inner','left_eye','left_eye_outer','right_eye_inner','right_eye','right_eye_outer','left_ear','right_ear','mouth_left','mouth_right','left_shoulder','right_shoulder','left_elbow','right_elbow','left_wrist','right_wrist','left_pinky','right_pinky','left_index','right_index','left_thumb','right_thumb','left_hip','right_hip','left_knee','right_knee','left_ankle','right_ankle','left_heel','right_heel','left_foot_index','right_foot_index'];
const connections:ReadonlyArray<readonly[string,string]>=[['left_shoulder','right_shoulder'],['left_shoulder','left_elbow'],['left_elbow','left_wrist'],['right_shoulder','right_elbow'],['right_elbow','right_wrist'],['left_shoulder','left_hip'],['right_shoulder','right_hip'],['left_hip','right_hip'],['left_hip','left_knee'],['left_knee','left_ankle'],['right_hip','right_knee'],['right_knee','right_ankle']];
const DYNAMIC_PREVIEW_MS=4500;
export function Practice2Screen({embedded=false}:{embedded?:boolean}){
 const camera=usePractice2Camera(),[mobileMode,setMobileMode]=useState<'static'|'dynamic'>('static'),[selectedStatic,setSelectedStatic]=useState(0),[selectedFlow,setSelectedFlow]=useState(0),[staticActive,setStaticActive]=useState(false),[staticSeconds,setStaticSeconds]=useState(0),[staticAnalysis,setStaticAnalysis]=useState<Practice2Analysis|null>(null),[dynamicRunning,setDynamicRunning]=useState(false),[dynamicElapsed,setDynamicElapsed]=useState(0),[dynamicAnalysis,setDynamicAnalysis]=useState<Practice2Analysis|null>(null);
 const staticHistory=useRef<Practice2PoseSample[]>([]),dynamicHistory=useRef<Practice2PoseSample[]>([]),dynamicStartedAt=useRef(0),dynamicCarried=useRef(0);
 const selectedPractice=staticPracticeDefinitions[selectedStatic],targetPose=staticReferencePoses[selectedPractice.id],flow=shortFlowDefinitions[selectedFlow],flowDurationMs=DYNAMIC_PREVIEW_MS,flowFrames=useMemo(()=>buildShortFlowReferenceFrames(flow,DYNAMIC_PREVIEW_MS),[flow]),activeFlowStep=shortFlowStepAt(flow,dynamicElapsed,flowDurationMs),reference=interpolatePractice2Reference(dynamicElapsed,flowFrames);

 useEffect(()=>{if(!staticActive)return;const timer=setInterval(()=>setStaticSeconds(value=>value+1),1000);return()=>clearInterval(timer)},[staticActive]);
 useEffect(()=>{if(staticActive&&staticSeconds*1000>=selectedPractice.holdDurationMs)setStaticActive(false)},[selectedPractice.holdDurationMs,staticActive,staticSeconds]);
 useEffect(()=>{if(!dynamicRunning)return;dynamicStartedAt.current=performance.now();let frame=0;const tick=(now:number)=>{const next=Math.min(flowDurationMs,dynamicCarried.current+now-dynamicStartedAt.current);setDynamicElapsed(next);if(next>=flowDurationMs){dynamicCarried.current=flowDurationMs;setDynamicRunning(false);return}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[dynamicRunning,flowDurationMs]);
 useEffect(()=>{if(!camera.pose.length)return;const timestamp=Date.now();if(staticActive){const sample={timestampMs:timestamp,keypoints:camera.pose};staticHistory.current=[...staticHistory.current.slice(-29),sample];setStaticAnalysis(analyzeStaticPractice(staticHistory.current,sample,targetPose))}if(dynamicRunning){const sample={timestampMs:dynamicElapsed,keypoints:camera.pose};dynamicHistory.current=[...dynamicHistory.current.slice(-49),sample];setDynamicAnalysis(analyzeDynamicMovement(dynamicHistory.current,sample,flowFrames))}},[camera.pose,dynamicElapsed,dynamicRunning,flowFrames,staticActive,targetPose]);

 const beginStatic=async()=>{await camera.start();staticHistory.current=[];setStaticSeconds(0);setStaticAnalysis(null);setStaticActive(true)};
 const finishStatic=()=>setStaticActive(false);
 const beginDynamic=async()=>{await camera.start();dynamicHistory.current=[];dynamicCarried.current=0;setDynamicElapsed(0);setDynamicAnalysis(null);setDynamicRunning(true)};
 const toggleDynamic=()=>setDynamicRunning(current=>{if(current){dynamicCarried.current=dynamicElapsed}else if(dynamicElapsed>=flowDurationMs){dynamicCarried.current=0;setDynamicElapsed(0)}return!current});

 return <main className={`${styles.page} ${embedded?styles.embedded:''}`}>
  {!embedded?<header className={styles.header}><Link href="/" className={styles.brand}><i/>SHIBASHI <span>EFE</span></Link><div><h1>PRATİK MODU</h1><p>Alıştır. Hisset. Ustalık Kazan.</p></div><Link href="/">Uygulamaya dön</Link></header>:<div className={styles.embeddedTitle}><p>PRATİK2 · GERÇEK ANALİZ</p><h1>Pratik Modu</h1><span>Statik duruş ve dinamik akış aynı ölçüm dilinde.</span></div>}
  <div className={styles.segment}><button className={mobileMode==='static'?styles.segmentActive:''} onClick={()=>setMobileMode('static')} type="button">1 · Statik Pozlar</button><button className={mobileMode==='dynamic'?styles.segmentActive:''} onClick={()=>setMobileMode('dynamic')} type="button">2 · Akış Hareketleri</button></div>
  <div className={styles.singleScreen}>
   {mobileMode==='static'?<section className={styles.module}>
    <ModuleHeader index="1" title="Statik Poz – Duruş Pratiği" note="Seçilen duruşu koru. Sistem gerçek landmark verisini analiz eder." action="Duruş Alıştırması"/>
    <div className={styles.staticPicker}>{staticPracticeDefinitions.map((item,index)=><button className={selectedStatic===index?styles.staticSelected:''} key={item.id} onClick={()=>{setSelectedStatic(index);setStaticAnalysis(null);setStaticActive(false)}} type="button"><img alt="" src={item.referenceImage}/><span><b>{String(item.order).padStart(2,'0')} · {item.title}</b><small>{item.englishTitle} · {item.cameraView}</small></span></button>)}</div>
    <div className={styles.staticStage}><CameraSurface camera={camera} placeholder={selectedPractice.referenceImage}/><div className={styles.stageShade}/><div className={styles.poseTarget}><small>HEDEF POZ</small><PoseFigure pose={targetPose}/><span>{selectedPractice.title}</span></div><div className={styles.stageBadge}><small>{selectedPractice.englishTitle.toUpperCase()}</small><strong>{selectedPractice.title}</strong><span>{selectedPractice.shortInstruction}</span></div><div className={styles.stageTime}><strong>{formatTime(staticSeconds)}</strong><small>{Math.round(selectedPractice.holdDurationMs/1000)} sn tut</small></div><ScoreRing score={staticAnalysis?.overallScore??null} label="Genel uyum"/><div className={styles.breathBar}><span>NEFES</span><strong>{staticActive?selectedPractice.breathingCue:'Doğal nefesine dön'}</strong><i/></div></div>
    <div className={styles.lowerGrid}><MetricPanel title="Metrik Analizi" analysis={staticAnalysis} fallback="Kamerayı açtığında gerçek ölçümler burada görünür."/><FeedbackPanel analysis={staticAnalysis}/></div>
    <div className={styles.actions}><button onClick={finishStatic} type="button">Duruşu bitir</button><div><button onClick={()=>setSelectedStatic(value=>(value+4)%5)} type="button">‹</button><span>{selectedStatic+1} / 5</span><button onClick={()=>setSelectedStatic(value=>(value+1)%5)} type="button">›</button></div><button className={styles.primary} onClick={beginStatic} type="button">{staticActive?'Tekrar dene':'Kamerayı aç ve dene'}</button></div>
   </section>:null}

   {mobileMode==='dynamic'?<section className={styles.module}>
    <ModuleHeader index="2" title="Dinamik Hareket – Akış Pratiği" note="Referans dizisini izle ve aynı akışı kamera önünde uygula." action="Akış Alıştırması"/>
    <div className={styles.flowPicker}>{shortFlowDefinitions.map((item,index)=><button className={selectedFlow===index?styles.flowSelected:''} key={item.id} onClick={()=>{setSelectedFlow(index);setDynamicRunning(false);setDynamicAnalysis(null);setDynamicElapsed(0)}} type="button"><span>{String(item.order).padStart(2,'0')}</span><strong>{item.title}</strong><small>4,5 sn · hareket ön izlemesi</small><em>{item.focus}</em></button>)}</div>
    <div className={styles.storyboard}>{flow.steps.map((item,index)=>{const practice=getStaticPractice(item.practiceId);return <article key={`${flow.id}-${item.practiceId}`}><img alt="" src={practice.referenceImage}/><span>{formatTime(Math.round(item.durationMs/1000))}</span><strong>{practice.title}</strong><small>{item.cue}</small></article>})}<div><small>SEÇİLİ KISA AKIŞ</small><strong>{flow.title}</strong><span>{flow.description}</span></div></div>
    <div className={styles.referenceRow}><div className={styles.referenceMedia}><img key={`${flow.id}-${activeFlowStep.practiceId}`} alt={`${flow.title} referans sahnesi`} src={getStaticPractice(activeFlowStep.practiceId).referenceImage}/><div className={styles.stageShade}/><span className={styles.referenceLabel}>4,5 SANİYELİK HAREKET</span><div className={styles.referenceFigure}><PoseFigure pose={reference.keypoints}/></div><div className={styles.referenceInfo}><strong>{flow.title}</strong><small>Yalnızca Pratik2 görsel serisi · {flow.focus}</small></div><div className={styles.referenceControls}><button onClick={toggleDynamic} type="button">{dynamicRunning?'Ⅱ':'▶'}</button><span>{(dynamicElapsed/1000).toFixed(1)} / 4,5 sn</span><div><i style={{width:`${dynamicElapsed/flowDurationMs*100}%`}}/></div></div></div><div className={styles.phases}><p>HAREKETİN EVRELERİ</p><div>{flow.steps.map((item,index)=>{const practice=getStaticPractice(item.practiceId);return <article className={item.practiceId===activeFlowStep.practiceId?styles.phaseActive:''} key={`${flow.id}-${item.practiceId}`}><PoseFigure pose={staticReferencePoses[item.practiceId]}/><span>{index+1}</span><small>{practice.title}</small></article>})}</div><footer><span>{activeFlowStep.cue}</span><strong>Evre {flow.steps.findIndex(item=>item.practiceId===activeFlowStep.practiceId)+1} / 3</strong></footer></div></div>
    <div className={styles.dynamicLower}><div className={styles.dynamicCamera}><CameraSurface camera={camera}/><div className={styles.stageShade}/><span className={styles.liveLabel}>CANLI PRATİK</span><div className={styles.liveTime}><strong>{(dynamicElapsed/1000).toFixed(1)}</strong><small>Süre</small></div><ScoreRing score={dynamicAnalysis?.overallScore??null} label="Genel uyum"/><div className={styles.liveTimeline}>{flow.steps.map(item=><i className={item.practiceId===activeFlowStep.practiceId?styles.timelineActive:''} key={`${flow.id}-${item.practiceId}`}/>)}</div></div><MetricPanel title="Akış Analizi" analysis={dynamicAnalysis} compact fallback="Akışı başlatınca zaman serisi ölçümleri görünür."/></div>
    <FeedbackPanel analysis={dynamicAnalysis}/>
    <div className={styles.actions}><button onClick={()=>setDynamicRunning(false)} type="button">Akışı bitir</button><div><button onClick={()=>setSelectedFlow(value=>(value+4)%5)} type="button">‹</button><span>{selectedFlow+1} / 5</span><button onClick={()=>setSelectedFlow(value=>(value+1)%5)} type="button">›</button></div><button className={styles.primary} onClick={beginDynamic} type="button">Akışı izle ve dene</button></div>
   </section>:null}
  </div>
  <video className={styles.detectorVideo} muted playsInline ref={camera.detectorVideoRef}/>
 </main>;
}

function ModuleHeader({index,title,note,action}:{index:string;title:string;note:string;action:string}){return <div className={styles.moduleHeader}><div><h2>{index}. {title}</h2><p>{note}</p></div><span>{action}</span></div>}
function ScoreRing({score,label}:{score:number|null;label:string}){return <div className={styles.scoreRing} style={{'--score':score??0}as CSSProperties}><strong>{score===null?'—':`${score}%`}</strong><small>{label}</small></div>}
function MetricPanel({title,analysis,fallback,compact=false}:{title:string;analysis:Practice2Analysis|null;fallback:string;compact?:boolean}){const metrics=analysis?.metrics??[];return <section className={`${styles.metricPanel} ${compact?styles.metricCompact:''}`}><h3>{title}</h3>{metrics.length?metrics.map(item=><div className={styles.metricRow} key={item.id}><div><strong>{item.label}</strong><small>{item.detail}</small></div>{item.available?<><span><i style={{width:`${item.value??0}%`}}/></span><b>{item.value}%</b></>:<em>Henüz ölçülemiyor</em>}</div>):<p className={styles.empty}>{fallback}</p>}{analysis?.overallScore!==null&&analysis?<div className={styles.metricTotal}><span>Toplam uyum</span><strong>{analysis.overallScore}%</strong></div>:null}</section>}
function FeedbackPanel({analysis}:{analysis:Practice2Analysis|null}){return <section className={styles.feedbackPanel}><h3>Geri Bildirim</h3>{analysis?.correction?<p className={styles.correction}><span>△</span>{analysis.correction}</p>:null}{analysis?.positive?<p className={styles.positive}><span>✓</span>{analysis.positive}</p>:null}{!analysis?<p className={styles.empty}>Aynı anda yalnızca bir düzeltme ve bir olumlu işaret göreceksin.</p>:null}<div className={styles.master}><small>USTADAN NOT</small><strong>“Duruş, hareketin köküdür. Kökün güçlenirse dalın hafifler.”</strong></div></section>}
function PoseFigure({pose}:{pose:readonly Practice2PosePoint[]}){const find=(name:string)=>pose.find(item=>item.name===name);return <svg viewBox="0 0 100 100" aria-hidden="true">{connections.map(([a,b])=>{const p1=find(a),p2=find(b);return p1&&p2?<line key={`${a}-${b}`} x1={p1.x*100} y1={p1.y*100} x2={p2.x*100} y2={p2.y*100}/>:null})}{pose.filter(item=>connections.flat().includes(item.name)).map(item=><circle key={item.name} cx={item.x*100} cy={item.y*100} r="1.4"/>)}</svg>}
function CameraSurface({camera,placeholder}:{camera:ReturnType<typeof usePractice2Camera>;placeholder?:string}){const videoRef=useRef<HTMLVideoElement>(null),canvasRef=useRef<HTMLCanvasElement>(null);useEffect(()=>{const video=videoRef.current;if(!video||!camera.stream)return;video.srcObject=camera.stream;void video.play()},[camera.stream]);useEffect(()=>drawPose(canvasRef.current,videoRef.current,camera.pose),[camera.pose]);return <>{placeholder&&camera.status!=='ready'?<img alt="Seçili statik duruş referansı" className={styles.stagePlaceholder} src={placeholder}/>:null}<video className={styles.cameraVideo} muted playsInline ref={videoRef}/><canvas className={styles.poseCanvas} ref={canvasRef}/>{camera.status!=='ready'&&!placeholder?<div className={styles.cameraEmpty}><span>{camera.status==='requesting'?'Kamera izni bekleniyor':camera.status==='denied'?'Kamera izni verilmedi':camera.status==='error'?'Kamera açılamadı':'Kamera başlatılmadı'}</span></div>:null}</>}
function usePractice2Camera(){const detectorVideoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),animationRef=useRef(0),[stream,setStream]=useState<MediaStream|null>(null),[pose,setPose]=useState<Practice2PosePoint[]>([]),[status,setStatus]=useState<'idle'|'requesting'|'ready'|'denied'|'error'>('idle');const start=useCallback(async()=>{if(streamRef.current)return;setStatus('requesting');try{const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false}),video=detectorVideoRef.current;streamRef.current=next;setStream(next);if(!video)return;video.srcObject=next;await video.play();const{createPoseLandmarker}=await import('@/lib/pose/createPoseLandmarker'),detector=await createPoseLandmarker();let last=0;const run=(now:number)=>{animationRef.current=requestAnimationFrame(run);if(now-last<100||video.readyState<2)return;last=now;const result=detector.detectForVideo(video,now),landmarks=result.landmarks[0];if(!landmarks?.length){setPose([]);return}setPose(landmarks.map((item,index)=>({name:landmarkNames[index]??`point-${index}`,x:item.x,y:item.y,z:item.z,score:item.visibility??1})))};setStatus('ready');animationRef.current=requestAnimationFrame(run)}catch(error){setStatus(error instanceof DOMException&&(error.name==='NotAllowedError'||error.name==='PermissionDeniedError')?'denied':'error')}},[]);useEffect(()=>()=>{cancelAnimationFrame(animationRef.current);streamRef.current?.getTracks().forEach(track=>track.stop())},[]);return{detectorVideoRef,pose,start,status,stream}}
function drawPose(canvas:HTMLCanvasElement|null,video:HTMLVideoElement|null,pose:readonly Practice2PosePoint[]){if(!canvas||!video)return;const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(rect.height*ratio));const context=canvas.getContext('2d');if(!context)return;context.setTransform(ratio,0,0,ratio,0,0);context.clearRect(0,0,rect.width,rect.height);const sourceWidth=video.videoWidth||rect.width,sourceHeight=video.videoHeight||rect.height,scale=Math.max(rect.width/sourceWidth,rect.height/sourceHeight),offsetX=(rect.width-sourceWidth*scale)/2,offsetY=(rect.height-sourceHeight*scale)/2,get=(name:string)=>{const item=pose.find(point=>point.name===name&&(point.score??1)>=.42);if(!item)return null;return{x:rect.width-(item.x*sourceWidth*scale+offsetX),y:item.y*sourceHeight*scale+offsetY}};context.lineCap='round';context.lineWidth=2.2;context.strokeStyle='rgba(169,217,119,.82)';for(const[a,b]of connections){const p1=get(a),p2=get(b);if(!p1||!p2)continue;context.beginPath();context.moveTo(p1.x,p1.y);context.lineTo(p2.x,p2.y);context.stroke()}for(const name of new Set(connections.flat())){const point=get(name);if(!point)continue;context.fillStyle='#F2EEE7';context.beginPath();context.arc(point.x,point.y,4.3,0,Math.PI*2);context.fill();context.fillStyle='#A9D977';context.beginPath();context.arc(point.x,point.y,2.6,0,Math.PI*2);context.fill()}}
function formatTime(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
