import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {Alert,Pressable,StyleSheet,Switch,Text,View} from 'react-native';
import {FiveShenSelector} from '../../components/FiveShenSelector';
import {Card,Eyebrow,Metric,Screen,Section,Title} from '../../components/ui';
import {colors} from '../../constants/theme';
import {getShen} from '../../data/fiveShen';
import {useApp} from '../../store/AppStore';
import {useShenExperience} from '../../store/ShenExperience';

export default function Profile(){
 const{profile,sessions,saveProfile,reset}=useApp();const{playing,toggleSound}=useShenExperience();const shen=getShen(profile.selectedShenId);
 const rows=[['camera-outline','Kamera ayarları'],['shield-checkmark-outline','Gizlilik'],['information-circle-outline','Shibashi hakkında']] as const;
 return <Screen>
  <View style={p.head}><View style={[p.avatar,{borderColor:shen.color}]}><Text style={[p.initial,{color:shen.color}]}>{profile.name[0]?.toUpperCase()}</Text></View><View><Eyebrow>SEVİYE 3 · AKIŞ ÖĞRENCİSİ</Eyebrow><Title>{profile.name}</Title><Text style={p.muted}>{profile.experience}</Text></View></View>
  <View style={p.metrics}><Metric label="Toplam pratik" value={sessions.length}/><Metric label="Dakika" value={sessions.reduce((a,s)=>a+s.duration,0)}/><Metric label="Durak" value={`${Math.min(8,1+Math.floor(sessions.length/3))}/8`}/></View>
  <Section title="Sana iyi gelen mod" action="Günlük önerilerini belirler">
   <FiveShenSelector selected={profile.selectedShenId} onSelect={selectedShenId=>saveProfile({selectedShenId})}/>
   <Pressable onPress={()=>router.push(`/shen/${shen.id}`)}><Card style={[p.shenCard,{borderColor:`${shen.color}66`}]}><View style={[p.shenSymbol,{backgroundColor:`${shen.color}18`}]}><Text style={{color:shen.color,fontSize:27}}>{shen.symbol}</Text></View><View style={{flex:1,gap:3}}><Text style={[p.shenMode,{color:shen.color}]}>{shen.dailyName.toUpperCase()}</Text><Text style={p.shenTitle}>{shen.label}</Text><Text style={p.muted}>{shen.note}</Text><Text style={[p.term,{color:shen.color}]}>Geleneksel adı: {shen.name} Shen · {shen.organ}</Text></View><Ionicons name="chevron-forward" color={shen.color} size={20}/></Card></Pressable>
  </Section>
  <Section title="Tercihler"><Card style={{paddingVertical:4}}><View style={p.row}><View style={p.rowLabel}><Ionicons name={playing?'musical-notes':'volume-mute-outline'} color={shen.color} size={21}/><View><Text style={p.text}>Arka plan müziği</Text><Text style={p.muted}>{playing?`${shen.dailyName} müziği çalıyor`:'Müzik kapalı'}</Text></View></View><Switch value={profile.soundEnabled} onValueChange={toggleSound} trackColor={{false:colors.surface2,true:shen.color}}/></View><View style={p.row}><View style={p.rowLabel}><Ionicons name="notifications-outline" color={shen.color} size={21}/><Text style={p.text}>Günlük hatırlatma</Text></View><Switch value={profile.reminders} onValueChange={v=>saveProfile({reminders:v})} trackColor={{false:colors.surface2,true:shen.color}}/></View><View style={p.row}><View style={p.rowLabel}><Ionicons name="time-outline" color={shen.color} size={21}/><Text style={p.text}>Günlük hedef</Text></View><Text style={[p.gold,{color:shen.color}]}>{profile.dailyGoal} dk</Text></View><Pressable onPress={()=>{saveProfile({onboardingDone:false,onboardingVersion:0});router.replace('/welcome')}} style={p.row}><View style={p.rowLabel}><Ionicons name="play-circle-outline" color={shen.color} size={21}/><Text style={p.text}>Giriş ve rehberi yeniden aç</Text></View><Ionicons name="chevron-forward" color={colors.muted}/></Pressable>{rows.map(([icon,label])=><Pressable key={label} style={p.row}><View style={p.rowLabel}><Ionicons name={icon} color={shen.color} size={21}/><Text style={p.text}>{label}</Text></View><Ionicons name="chevron-forward" color={colors.muted}/></Pressable>)}</Card></Section>
  <Pressable onPress={()=>Alert.alert('Verileri sıfırla','Tüm pratik ve günlük verilerin silinecek.',[{text:'Vazgeç'},{text:'Sıfırla',style:'destructive',onPress:reset}])}><Text style={p.reset}>Tüm verileri sıfırla</Text></Pressable><Text style={[p.muted,{textAlign:'center'}]}>Shibashi 1.0.0 · Verilerin cihazında saklanır</Text>
 </Screen>
}
const p=StyleSheet.create({head:{flexDirection:'row',gap:15,alignItems:'center'},avatar:{width:68,height:68,borderRadius:34,backgroundColor:colors.surface2,borderWidth:1,alignItems:'center',justifyContent:'center'},initial:{fontSize:27,fontWeight:'800'},muted:{color:colors.muted,fontSize:13,lineHeight:18},term:{fontSize:10,fontWeight:'700'},metrics:{flexDirection:'row',gap:8},shenCard:{flexDirection:'row',alignItems:'center',gap:12},shenSymbol:{width:52,height:52,borderRadius:26,alignItems:'center',justifyContent:'center'},shenMode:{fontSize:9,fontWeight:'900',letterSpacing:1.2},shenTitle:{color:colors.cream,fontSize:15,fontWeight:'700'},row:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:colors.line},rowLabel:{flexDirection:'row',alignItems:'center',gap:12},text:{color:colors.cream,fontSize:15},gold:{color:colors.gold,fontWeight:'700'},reset:{color:colors.danger,textAlign:'center',fontWeight:'700',padding:12}});
