import type{BodyTraceObservation,BodyTraceResult,BodyView,FirstMovementResult,OnboardingPosePoint,PoseSample,PracticeMetric}from'./types';

const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
const median=(values:number[])=>{if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2};
const get=(points:OnboardingPosePoint[],name:string)=>points.find(point=>point.name===name);
const lineTilt=(a:OnboardingPosePoint,b:OnboardingPosePoint)=>Math.abs(Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI);
const horizontalTilt=(a:OnboardingPosePoint,b:OnboardingPosePoint)=>{const angle=lineTilt(a,b);return Math.min(angle,Math.abs(180-angle))};
const scoreDeviation=(value:number,soft:number,limit:number)=>clamp(100-Math.max(0,value-soft)/Math.max(1,limit-soft)*100);
const metric=(id:string,label:string,value:number,detail:string):PracticeMetric=>({id,label,value:clamp(value),available:true,detail});

export function poseConfidence(points:OnboardingPosePoint[]){const required=['nose','left_shoulder','right_shoulder','left_hip','right_hip','left_knee','right_knee','left_ankle','right_ankle'];const visible=required.map(name=>get(points,name)?.score??0);return visible.reduce((sum,value)=>sum+value,0)/visible.length}
export function isFullBodyReady(points:OnboardingPosePoint[]){const confidence=poseConfidence(points),ys=['nose','left_ankle','right_ankle'].map(name=>get(points,name)?.y).filter((value):value is number=>typeof value==='number');return confidence>=.5&&ys.length===3&&Math.max(...ys)-Math.min(...ys)>=.52}

function sampleMetrics(points:OnboardingPosePoint[],view:BodyView){const ls=get(points,'left_shoulder'),rs=get(points,'right_shoulder'),lh=get(points,'left_hip'),rh=get(points,'right_hip'),la=get(points,'left_ankle'),ra=get(points,'right_ankle'),nose=get(points,'nose');if(!ls||!rs||!lh||!rh||!la||!ra||!nose)return null;const shoulderTilt=horizontalTilt(ls,rs),hipTilt=horizontalTilt(lh,rh),shoulderCenter={x:(ls.x+rs.x)/2,y:(ls.y+rs.y)/2},hipCenter={x:(lh.x+rh.x)/2,y:(lh.y+rh.y)/2},axis=Math.abs(Math.atan2(shoulderCenter.x-hipCenter.x,hipCenter.y-shoulderCenter.y)*180/Math.PI),stance=Math.abs(la.x-ra.x)/Math.max(.08,Math.abs(ls.x-rs.x));return{view,shoulderTilt,hipTilt,axis,stance,confidence:poseConfidence(points)}}

export function analyzeBodyTrace(samples:Record<BodyView,PoseSample[]>):BodyTraceResult{const rows=(Object.keys(samples)as BodyView[]).flatMap(view=>samples[view].map(sample=>sampleMetrics(sample.keypoints,view)).filter(Boolean)) as NonNullable<ReturnType<typeof sampleMetrics>>[];const byView=(view:BodyView)=>rows.filter(row=>row.view===view),front=byView('front'),side=byView('side'),back=byView('back');const shoulder=median([...front,...back].map(row=>row.shoulderTilt)),hip=median([...front,...back].map(row=>row.hipTilt)),axis=median(rows.map(row=>row.axis)),stance=median(front.map(row=>row.stance)),confidence=median(rows.map(row=>row.confidence));const metrics=[metric('shoulder','Omuz hattı',scoreDeviation(shoulder,1.5,11),`${shoulder.toFixed(1)}° yatay fark`),metric('hip','Kalça hattı',scoreDeviation(hip,1.5,10),`${hip.toFixed(1)}° yatay fark`),metric('axis','Gövde ekseni',scoreDeviation(axis,1.5,12),`${axis.toFixed(1)}° eğim`),metric('stance','Temel duruş',scoreDeviation(Math.abs(stance-1.25),.18,.8),`Omuz genişliğinin ${stance.toFixed(1)} katı`)];const observations:BodyTraceObservation[]=[];observations.push(shoulder<4?{id:'shoulder',status:'positive',text:'Omuz hattın dengeli.',metricSource:'shoulderTilt'}:{id:'shoulder',status:'attention',text:'Omuzlarından birini yumuşakça biraz daha bırakabilirsin.',metricSource:'shoulderTilt'});if(axis>=4)observations.push({id:'axis',status:'attention',text:'Merkez hattın bir yana hafifçe yaklaşıyor; ayak tabanlarını eşit hissetmeyi dene.',metricSource:'axisTilt'});else observations.push({id:'axis',status:'positive',text:'Gövde eksenin sakin ve dengeli görünüyor.',metricSource:'axisTilt'});observations.push(stance<.9?{id:'stance',status:'neutral',text:'Başlangıçta biraz daha geniş bir temel duruş sana iyi gelebilir.',metricSource:'stanceRatio'}:{id:'stance',status:'positive',text:'Ayakların dengeli bir başlangıç alanı oluşturuyor.',metricSource:'stanceRatio'});return{frontCaptured:front.length>0,sideCaptured:side.length>0,backCaptured:back.length>0,observations:observations.slice(0,3),confidence,metrics}}

export function analyzeFirstMovement(samples:PoseSample[]):FirstMovementResult{const valid=samples.map(sample=>sampleMetrics(sample.keypoints,'front')).filter(Boolean)as NonNullable<ReturnType<typeof sampleMetrics>>[];const confidence=median(valid.map(row=>row.confidence));if(valid.length<3||confidence<.45)return{completed:false,metrics:[],confidence};const shoulder=median(valid.map(row=>row.shoulderTilt)),hip=median(valid.map(row=>row.hipTilt)),axis=median(valid.map(row=>row.axis)),stance=median(valid.map(row=>row.stance));const wristScores=samples.map(sample=>{const lw=get(sample.keypoints,'left_wrist'),rw=get(sample.keypoints,'right_wrist'),lh=get(sample.keypoints,'left_hip'),rh=get(sample.keypoints,'right_hip');if(!lw||!rw||!lh||!rh)return 0;return scoreDeviation((Math.abs(lw.y-lh.y)+Math.abs(rw.y-rh.y))/2,.05,.32)}).filter(Boolean);const symmetry=scoreDeviation(Math.abs(shoulder-hip),1,10),stability=scoreDeviation(Math.max(0,...valid.map((row,index)=>index?Math.abs(row.axis-valid[index-1].axis):0)),.6,7);const metrics=[metric('shoulder','Omuz hizası',scoreDeviation(shoulder,1.5,11),`${shoulder.toFixed(1)}° fark`),metric('hip','Kalça hizası',scoreDeviation(hip,1.5,10),`${hip.toFixed(1)}° fark`),metric('torso','Gövde eğimi',scoreDeviation(axis,1.5,12),`${axis.toFixed(1)}°`),metric('stance','Ayak mesafesi',scoreDeviation(Math.abs(stance-1.15),.2,.85),`${stance.toFixed(1)}× omuz`),metric('arms','Kol konumu',median(wristScores),`Kollar doğal hatta`),metric('symmetry','Sağ-sol simetri',symmetry,`Omuz ve kalça uyumu`),metric('stability','Stabilite',stability,`${valid.length} gerçek kare`)];const overallScore=Math.round(metrics.reduce((sum,item)=>sum+(item.value??0),0)/metrics.length);const weakest=[...metrics].sort((a,b)=>(a.value??0)-(b.value??0))[0];const correction=weakest.value!<70?(weakest.id==='shoulder'?'Omuzlarını yumuşakça biraz daha rahat bırakabilirsin.':weakest.id==='stance'?'Ayaklarını omuz genişliğine biraz daha yaklaştırmayı deneyebilirsin.':'Merkezini iki ayağın arasında biraz daha sakin tutmayı deneyebilirsin.'):undefined;return{overallScore,completed:true,positiveFeedback:overallScore>=78?'Gövden dik ve dengeli. Güzel.':'Harekete yaklaşıyorsun; nefesini doğal tut.',correctionFeedback:correction,metrics,confidence}}

