import{dynamicMetricWeights,practice2MinimumLandmarks}from'./config';
import{interpolatePractice2Reference,practice2Movement}from'./data';
import{angle,distance,errorScore,metric,normalizePose,visible,weightedScore}from'./math';
import type{Practice2Analysis,Practice2Metric,Practice2PoseSample,Practice2ReferenceFrame}from'./types';

export function analyzeDynamicMovement(history:readonly Practice2PoseSample[],now:Practice2PoseSample,referenceFrames:readonly Practice2ReferenceFrame[]=practice2Movement.referenceFrames):Practice2Analysis{
 const required=['left_shoulder','right_shoulder','left_elbow','right_elbow','left_wrist','right_wrist','left_hip','right_hip','left_knee','right_knee','left_ankle','right_ankle'],count=required.filter(name=>visible(now.keypoints,name)).length,confidence=count/required.length;
 if(count<practice2MinimumLandmarks)return{overallScore:null,confidence,metrics:[],correction:'Tam bedenini kamera içinde tut.'};
 const reference=interpolatePractice2Reference(now.timestampMs,referenceFrames),user=normalizePose(now.keypoints),target=normalizePose(reference.keypoints);if(!user||!target)return{overallScore:null,confidence,metrics:[],correction:'Omuz ve kalça hattını görünür tut.'};
 const u=(name:string)=>visible(user,name)!,t=(name:string)=>visible(target,name)!;
 const wristError=(distance(u('left_wrist'),t('left_wrist'))+distance(u('right_wrist'),t('right_wrist')))/2,movementPath=errorScore(wristError,1.25);
 const userElbows=[angle(u('left_shoulder'),u('left_elbow'),u('left_wrist')),angle(u('right_shoulder'),u('right_elbow'),u('right_wrist'))],targetElbows=[angle(t('left_shoulder'),t('left_elbow'),t('left_wrist')),angle(t('right_shoulder'),t('right_elbow'),t('right_wrist'))],armSync=errorScore((Math.abs(userElbows[0]-targetElbows[0])+Math.abs(userElbows[1]-targetElbows[1]))/2,70);
 const torsoRotation=errorScore(Math.abs(distance(u('left_shoulder'),u('right_shoulder'))-distance(t('left_shoulder'),t('right_shoulder'))),.42),hipMid=(u('left_hip').x+u('right_hip').x)/2,ankleMid=(u('left_ankle').x+u('right_ankle').x)/2,weightTransfer=errorScore(Math.abs(hipMid-ankleMid),.55);
 const knees=Math.round((errorScore(Math.abs(angle(u('left_hip'),u('left_knee'),u('left_ankle'))-angle(t('left_hip'),t('left_knee'),t('left_ankle'))),55)+errorScore(Math.abs(angle(u('right_hip'),u('right_knee'),u('right_ankle'))-angle(t('right_hip'),t('right_knee'),t('right_ankle'))),55))/2);
 const duration=referenceFrames[referenceFrames.length-1]?.timestampMs??practice2Movement.durationMs,range=errorScore(Math.abs(distance(u('left_wrist'),u('right_wrist'))-distance(t('left_wrist'),t('right_wrist'))),.9),bestFrame=referenceFrames.map(frame=>{const normalized=normalizePose(frame.keypoints);if(!normalized)return{timestampMs:frame.timestampMs,error:99};const get=(name:string)=>visible(normalized,name)!;return{timestampMs:frame.timestampMs,error:(distance(u('left_wrist'),get('left_wrist'))+distance(u('right_wrist'),get('right_wrist')))/2}}).sort((a,b)=>a.error-b.error)[0],timing=errorScore(Math.abs(bestFrame.timestampMs-now.timestampMs),Math.max(1500,duration*.12)),fluidity=fluidityScore(history.slice(-10));
 const startMatch=now.timestampMs<=duration*.15?movementPath:null,endMatch=now.timestampMs>=duration*.85?movementPath:null;
 const metrics:Practice2Metric[]=[metric('timing','Zamanlama',timing,'Referans evreyle zaman farkı'),metric('movementPath','Hareket yolu',movementPath,'Bileklerin izlediği çizgi'),metric('armSync','Kol senkronu',armSync,'İki kolun ortak ritmi'),metric('fluidity','Akışkanlık',fluidity,fluidity===null?'Dört hareket karesi gerekli':'Hız değişiminin yumuşaklığı'),metric('torsoRotation','Gövde dönüşü',torsoRotation,'Omuz hattındaki dönüş'),metric('weightTransfer','Ağırlık aktarımı',weightTransfer,'Kalça merkezinin ayaklara göre geçişi'),metric('kneeAngle','Diz açısı',knees,'İki dizin referans açıları'),metric('range','Hareket genişliği',range,'Kolların açılma mesafesi'),metric('startMatch','Başlangıç uyumu',startMatch,'İlk evrede ölçülür'),metric('endMatch','Bitiş uyumu',endMatch,'Son evrede ölçülür')];
 const overallScore=weightedScore(metrics,dynamicMetricWeights),values=metrics.filter(item=>item.value!==null).sort((a,b)=>(a.value??0)-(b.value??0)),weak=values[0],strong=values[values.length-1];
 const correction=!weak||weak.value!<70?undefined:weak.id==='timing'?'Hareketi referansla aynı anda başlat.':weak.id==='movementPath'||weak.id==='range'?'İtme anında kollarını biraz daha uzat.':weak.id==='weightTransfer'?'Ağırlık geçişini biraz daha yavaş yap.':weak.id==='fluidity'?'Hızı değiştirirken hareketi kesme.':'Bitiş pozunu biraz daha uzun koru.';
 const positive=strong?.value&&strong.value>=78?(strong.id==='torsoRotation'?'Gövde dönüşün güzel.':strong.id==='armSync'?'Kolların aynı ritimde ilerliyor.':'Akışın referansla uyumlu.'):undefined;
 return{overallScore,confidence,metrics,correction,positive};
}

function fluidityScore(samples:readonly Practice2PoseSample[]){if(samples.length<4)return null;const velocities:number[]=[];for(let index=1;index<samples.length;index++){const before=visible(samples[index-1].keypoints,'left_wrist'),after=visible(samples[index].keypoints,'left_wrist'),delta=(samples[index].timestampMs-samples[index-1].timestampMs)/1000;if(before&&after&&delta>0)velocities.push(distance(before,after)/delta)}if(velocities.length<3)return null;const mean=velocities.reduce((sum,value)=>sum+value,0)/velocities.length,variance=velocities.reduce((sum,value)=>sum+(value-mean)**2,0)/velocities.length;return errorScore(Math.sqrt(variance),1.1)}
