import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {ImageBackground,Pressable,StyleSheet,Text,View} from 'react-native';
import {Card,Eyebrow,PrimaryButton,Screen,Section,Title} from '../../components/ui';
import {colors,radii} from '../../constants/theme';
import {movements} from '../../data/content';
import {movementImages} from '../../data/movementAssets';
import {getShen} from '../../data/fiveShen';
import {useApp} from '../../store/AppStore';
export default function MovementDetail(){const{id}=useLocalSearchParams<{id:string}>();const m=movements.find(x=>x.id===id)||movements[0];const{profile}=useApp();const shen=getShen(profile.selectedShenId);return <Screen><Pressable onPress={()=>router.back()} style={d.back}><Ionicons name="arrow-back" color={colors.cream} size={20}/><Text style={d.backText}>18 harekete dön</Text></Pressable><ImageBackground source={movementImages[m.order]} style={d.media} imageStyle={d.mediaImage}><View style={d.shade}/><View style={[d.play,{backgroundColor:shen.color}]}><Ionicons name="play" color={colors.ink} size={24}/></View><Text style={d.placeholder}>HAREKET REFERANSI · ÖNCE İZLE</Text><View style={d.mediaMeta}><Text style={d.mediaMetaText}>{m.duration} DK</Text><Text style={d.mediaMetaText}>{m.difficulty.toUpperCase()}</Text></View></ImageBackground><Eyebrow>HAREKET {m.order} · AŞAMA {m.gate} · {m.focus}</Eyebrow><Title>{m.name}</Title><Text style={[d.en,{color:shen.color}]}>{m.englishName}</Text><Text style={d.body}>{m.description}</Text><PrimaryButton label="Kamera ile Pratik Yap" icon="camera" onPress={()=>router.push(`/practice-session?movementId=${m.id}`)}/><Pressable onPress={()=>router.push({pathname:'/living-story/[id]',params:{id:`story-${m.order}`}})} style={[d.storyLink,{borderColor:`${shen.color}55`}]}><Ionicons name="sparkles-outline" color={shen.color} size={22}/><View style={{flex:1}}><Text style={[d.storyLabel,{color:shen.color}]}>YAŞAYARAK ÖĞREN</Text><Text style={d.storyTitle}>Bu hareketin gündelik hikâyesini aç</Text></View><Ionicons name="chevron-forward" color={colors.muted} size={19}/></Pressable><Section title="Hareket adımları">{m.steps.map((x,i)=><View key={x} style={d.step}><Text style={[d.num,{backgroundColor:shen.color}]}>{i+1}</Text><Text style={d.stepText}>{x}</Text></View>)}</Section><Section title="Nefes ritmi"><Card style={d.info}><Ionicons name="water-outline" color={shen.color} size={25}/><Text style={d.stepText}>{m.breath}</Text></Card></Section><Section title="Sık yapılan hatalar"><Card>{m.mistakes.map(x=><View key={x} style={d.bullet}><Text style={{color:colors.danger}}>•</Text><Text style={d.stepText}>{x}</Text></View>)}</Card></Section></Screen>}
const d=StyleSheet.create({back:{height:42,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{color:colors.muted,fontSize:13,fontWeight:'700'},media:{height:285,borderRadius:radii.lg,alignItems:'center',justifyContent:'center',gap:15,overflow:'hidden'},mediaImage:{borderRadius:radii.lg},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(3,13,11,.36)'},play:{width:58,height:58,borderRadius:29,alignItems:'center',justifyContent:'center'},placeholder:{color:colors.cream,fontSize:10,fontWeight:'900',letterSpacing:1.4},mediaMeta:{position:'absolute',left:14,right:14,bottom:14,flexDirection:'row',justifyContent:'space-between'},mediaMetaText:{color:colors.cream,fontSize:9,fontWeight:'900',backgroundColor:'rgba(3,13,11,.72)',borderRadius:radii.pill,paddingHorizontal:9,paddingVertical:6},en:{fontStyle:'italic',marginTop:-18},body:{color:colors.muted,fontSize:16,lineHeight:25},storyLink:{minHeight:74,borderRadius:radii.md,backgroundColor:colors.surface,borderWidth:1,padding:13,flexDirection:'row',alignItems:'center',gap:11},storyLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.1},storyTitle:{color:colors.cream,fontSize:13,fontWeight:'800',marginTop:4},step:{flexDirection:'row',gap:14,alignItems:'flex-start'},num:{width:30,height:30,borderRadius:15,color:colors.ink,textAlign:'center',lineHeight:30,fontWeight:'900'},stepText:{color:colors.cream,fontSize:15,lineHeight:23,flex:1},info:{flexDirection:'row',gap:12,alignItems:'center'},bullet:{flexDirection:'row',gap:10,marginVertical:5}});
