import {Ionicons} from '@expo/vector-icons';
import {CameraType,CameraView,useCameraPermissions} from 'expo-camera';
import {router,useLocalSearchParams} from 'expo-router';
import {useEffect,useMemo,useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {PrimaryButton} from '../components/ui';
import {colors,radii} from '../constants/theme';
import {movements,practices} from '../data/content';
import {MockPoseAnalyzer} from '../services/pose/PoseAnalyzer';
export default function PracticeSession(){
 const{practiceId,movementId}=useLocalSearchParams<{practiceId?:string;movementId?:string}>();const[permission,requestPermission]=useCameraPermissions();const[facing,setFacing]=useState<CameraType>('front'),[paused,setPaused]=useState(false),[seconds,setSeconds]=useState(0),[tick,setTick]=useState(0),[analysisLeft,setAnalysisLeft]=useState(0);const analyzer=useMemo(()=>new MockPoseAnalyzer(),[]);
 const practice=practices.find(x=>x.id===practiceId);const list=movementId?[movementId]:(practice?.movementIds||['movement-1']);const index=Math.min(list.length-1,Math.floor(seconds/25));const movement=movements.find(x=>x.id===list[index])||movements[0];
 useEffect(()=>{analyzer.startAnalysis();const id=setInterval(()=>{if(!paused){setSeconds(s=>s+1);analyzer.processFrame();setTick(t=>t+1)}},1000);return()=>{clearInterval(id);analyzer.stopAnalysis()}},[analyzer,paused]);
 useEffect(()=>{if(!analysisLeft)return;const id=setTimeout(()=>{if(analysisLeft===1){const x=analyzer.snapshot();router.replace({pathname:'/practice-result',params:{practiceId:practiceId||movementId||'free',duration:Math.max(1,Math.ceil(seconds/60)),posture:x.postureScore,balance:x.balanceScore,flow:x.flowScore}})}else setAnalysisLeft(v=>v-1)},1000);return()=>clearTimeout(id)},[analysisLeft,analyzer,practiceId,movementId,seconds]);
 const finish=()=>{setPaused(true);setAnalysisLeft(3)};
 if(!permission)return <View style={c.permission}/>;
 if(!permission.granted)return <SafeAreaView style={c.permission}><View style={c.permissionIcon}><Ionicons name="camera-outline" size={42} color={colors.gold}/></View><Text style={c.permissionTitle}>Kamera rehberini aç</Text><Text style={c.permissionBody}>Görüntün cihazından ayrılmaz. Kamera yalnızca hareket alanını göstermek ve duruş geri bildirimi hazırlamak için kullanılır.</Text><PrimaryButton label="Kameraya izin ver" icon="camera" onPress={requestPermission}/><Pressable onPress={()=>router.back()}><Text style={c.cancel}>Şimdi değil</Text></Pressable></SafeAreaView>;
 const scores=analyzer.snapshot();void tick;
 return <View style={c.root}><CameraView style={StyleSheet.absoluteFill} facing={facing} active={!paused} mirror={facing==='front'}/><View style={c.shade}/><SafeAreaView style={c.overlay}><View style={c.top}><Pressable onPress={()=>router.back()} style={c.icon}><Ionicons name="close" color="white" size={24}/></Pressable><View style={c.pill}><View style={c.live}/><Text style={c.pillText}>{analysisLeft?'ANALİZ EDİLİYOR':paused?'DURAKLATILDI':'CANLI HAREKET KOÇU'}</Text></View><Pressable onPress={()=>setFacing(f=>f==='front'?'back':'front')} style={c.icon}><Ionicons name="camera-reverse-outline" color="white" size={24}/></Pressable></View><View style={c.guide}><View style={c.head}/><View style={c.bodyLine}/><View style={c.arms}/><View style={c.legs}/></View><View style={c.coach}><Text style={c.coachLabel}>CANLI FORM ANALİZİ · {['HAZIRLAN','YÜKSELT','TUT','YUMUŞAT'][Math.min(3,Math.floor(seconds/8))]}</Text><Text style={c.coachText}>{analysisLeft?`Hareket kaliten ölçülüyor · ${analysisLeft}s`:scores.corrections[0]}</Text></View><View style={c.bottom}><View><Text style={c.step}>HAREKET {index+1}/{list.length} · {seconds}s</Text><Text style={c.title}>{movement.name}</Text><Text style={c.breath}>● Nefes al · kolları yumuşakça yükselt</Text></View><View style={c.scores}>{[['Duruş',scores.postureScore],['Akış',scores.flowScore],['Denge',scores.balanceScore]].map(([n,v])=><View key={String(n)} style={c.score}><Text style={c.scoreValue}>{v}</Text><Text style={c.scoreLabel}>{n}</Text></View>)}</View><View style={c.controls}><Pressable disabled={!!analysisLeft} onPress={()=>setPaused(v=>!v)} style={c.pause}><Ionicons name={paused?'play':'pause'} size={22} color={colors.cream}/><Text style={c.pauseText}>{paused?'Sürdür':'Duraklat'}</Text></Pressable><Pressable disabled={!!analysisLeft} onPress={finish} style={c.finish}><Text style={c.finishText}>{analysisLeft?'Ölçülüyor':'Bitir ve analiz et'}</Text></Pressable></View></View></SafeAreaView></View>
}
const c=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},shade:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'rgba(0,20,15,.18)'},overlay:{flex:1,justifyContent:'space-between'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:18},icon:{width:46,height:46,borderRadius:23,backgroundColor:'rgba(0,0,0,.35)',alignItems:'center',justifyContent:'center'},pill:{height:38,paddingHorizontal:14,borderRadius:19,backgroundColor:'rgba(0,0,0,.4)',flexDirection:'row',alignItems:'center',gap:7},live:{width:7,height:7,borderRadius:4,backgroundColor:colors.jade},pillText:{color:'white',fontSize:10,fontWeight:'800',letterSpacing:1},guide:{position:'absolute',top:'18%',left:'22%',right:'22%',height:'46%',borderWidth:1,borderColor:'rgba(240,200,122,.55)',borderRadius:100,alignItems:'center'},head:{width:52,height:52,borderRadius:26,borderWidth:1,borderColor:colors.amber,marginTop:18},bodyLine:{height:150,width:1,backgroundColor:colors.amber},arms:{position:'absolute',top:120,width:'90%',height:1,backgroundColor:colors.amber},legs:{width:120,height:120,borderLeftWidth:1,borderRightWidth:1,borderColor:colors.amber,transform:[{rotate:'16deg'}]},coach:{position:'absolute',left:20,right:20,bottom:278,backgroundColor:'rgba(7,21,18,.86)',padding:13,borderRadius:radii.md,borderWidth:1,borderColor:'rgba(105,181,141,.35)'},coachLabel:{color:colors.jade,fontSize:9,fontWeight:'800',letterSpacing:1},coachText:{color:colors.cream,fontSize:14,marginTop:4},bottom:{backgroundColor:'rgba(6,17,15,.94)',padding:20,gap:15,borderTopLeftRadius:26,borderTopRightRadius:26},step:{color:colors.gold,fontSize:10,fontWeight:'800',letterSpacing:1.1},title:{color:colors.cream,fontSize:22,fontWeight:'700',marginTop:4},breath:{color:colors.muted,fontSize:12,marginTop:4},scores:{flexDirection:'row',gap:8},score:{flex:1,alignItems:'center',backgroundColor:colors.surface,padding:9,borderRadius:12},scoreValue:{color:colors.jade,fontSize:18,fontWeight:'800'},scoreLabel:{color:colors.muted,fontSize:10},controls:{flexDirection:'row',gap:10},pause:{flex:1,height:50,borderRadius:25,backgroundColor:colors.surface2,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},pauseText:{color:colors.cream,fontWeight:'700'},finish:{width:100,height:50,borderRadius:25,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center'},finishText:{color:colors.ink,fontWeight:'800'},permission:{flex:1,backgroundColor:colors.ink,padding:28,alignItems:'center',justifyContent:'center',gap:20},permissionIcon:{width:90,height:90,borderRadius:45,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},permissionTitle:{color:colors.cream,fontSize:26,fontWeight:'700',textAlign:'center'},permissionBody:{color:colors.muted,fontSize:16,lineHeight:24,textAlign:'center'},cancel:{color:colors.muted,fontWeight:'600',padding:12}});
